// crates/gm_plugin_bitbucket/src/auth.rs
//
// Bitbucket authentication helpers.
//
// Bitbucket uses App Passwords for API access — not the user's account password.
// App Passwords are created per-user at the account settings page and are
// scoped to specific permissions. The credential stored in the vault is
// "username:app_password" (colon-separated).
//
// Required App Password permissions for Git Manager:
//   • Account:Read         — GET /user to validate and read the username
//   • Repositories:Read    — list and search repositories
//
// SSH-based git operations use the SSH key generated by the system, not the
// app password. The app password is only used for API calls (repository listing,
// authentication validation).

/// The credential format expected by the Bitbucket client.
/// Stored in the vault as "username:app_password".
pub const CREDENTIAL_FORMAT: &str = "username:app_password";

/// Required App Password permissions for full Git Manager functionality.
pub const REQUIRED_PERMISSIONS: &[&str] = &[
    "Account:Read",
    "Repositories:Read",
    "Repositories:Write",
];

/// Returns the App Password creation URL.
pub fn app_password_url() -> &'static str {
    "https://bitbucket.org/account/settings/app-passwords/"
}

/// Validates that a Bitbucket credential string has the expected format.
/// A valid credential contains exactly one colon separating username from password.
pub fn looks_like_valid_credential(credential: &str) -> bool {
    let parts: Vec<&str> = credential.splitn(2, ':').collect();
    if parts.len() != 2 { return false; }
    let username = parts[0].trim();
    let password = parts[1].trim();
    !username.is_empty() && password.len() >= 16
}

/// Returns a human-readable description of the credential format.
pub fn credential_format_description() -> &'static str {
    "Enter your Bitbucket credential as: username:app_password\n\
     Create an App Password at https://bitbucket.org/account/settings/app-passwords/\n\
     Required permissions: Account:Read, Repositories:Read"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn valid_credential() {
        assert!(looks_like_valid_credential("shakamoses:ABCDEFGHIJKLMNOPabcdefg"));
    }

    #[test]
    fn missing_colon_rejected() {
        assert!(!looks_like_valid_credential("just_a_token_with_no_colon"));
    }

    #[test]
    fn empty_password_rejected() {
        assert!(!looks_like_valid_credential("username:"));
        assert!(!looks_like_valid_credential("username:short"));
    }

    #[test]
    fn empty_username_rejected() {
        assert!(!looks_like_valid_credential(":ABCDEFGHIJKLMNOPQRSTUVWXYZ"));
    }
}