//! Application-wide compile-time constants.
//!
//! Every constant here is derived from a deliberate decision — none are
//! arbitrary. The comments explain the reasoning so that future maintainers
//! know whether changing a value is safe or has downstream consequences.

/// The SSH configuration directory relative to the user's home directory.
/// This is fixed by the OpenSSH specification — do not change it.
pub const SSH_DIR: &str = ".ssh";

/// The application's configuration directory relative to the user's home directory.
/// Files here: config.json, web_token, secrets.enc (fallback keyring).
/// This directory is created with mode 0700 on first run.
pub const CONFIG_DIR_NAME: &str = ".git-zyrix";

/// Default SSH key type for new keys generated by the system.
/// Ed25519 is chosen over RSA because:
///   - Smaller keys (256 bits vs 3072+ bits for equivalent security)
///   - Faster signing and verification
///   - Fixed key size eliminates the "how many bits?" choice for users
///   - Supported by all major Git hosting platforms since 2014
pub const DEFAULT_SSH_KEY_TYPE: &str = "ed25519";

/// Default Git branch name for newly initialized repositories.
/// "main" is the modern default (GitHub changed in 2020; GitLab and Bitbucket
/// followed). We use "main" to match new repository defaults on all major platforms.
pub const DEFAULT_BRANCH: &str = "main";

/// Minimum allowed length for account aliases (inclusive).
/// "a" is too short to be a meaningful human-readable identifier.
pub const ALIAS_MIN_LENGTH: usize = 2;

/// Maximum allowed length for account aliases (inclusive).
/// 50 characters is enough for any descriptive alias while keeping
/// the SSH host alias (alias is embedded in it: "github.com-work") manageable.
pub const ALIAS_MAX_LENGTH: usize = 50;

/// The "User" field value in SSH config Host blocks for git operations.
/// All major Git hosting platforms use "git" as the SSH username.
/// Users authenticate via their SSH key, not the username.
pub const GIT_SSH_USER: &str = "git";

/// The default SSH port for git operations.
/// Standard SSH port is 22. Some firewalls block port 22; GitHub also
/// supports SSH over port 443 (configured per-account if needed).
pub const DEFAULT_SSH_PORT: u16 = 22;

/// The web interface binding address for local-only access.
/// 127.0.0.1 ensures the web interface is only accessible from the local machine.
/// Binding to 0.0.0.0 would expose it to the network — never do this by default.
pub const DEFAULT_WEB_ADDR: &str = "127.0.0.1:5008";

/// The GIT_SSH_COMMAND timeout in seconds for SSH connection attempts.
/// 30 seconds is generous enough for slow networks while preventing
/// indefinite hangs when a server is unreachable.
pub const SSH_CONNECT_TIMEOUT_SECS: u32 = 30;

/// The application name used in keychain entries, audit log actor fields,
/// and SSH key comments. Must be stable — changing this would orphan
/// credentials stored under the old name in the system keychain.
pub const APP_NAME: &str = "git-zyrix";

/// The current event schema version string.
/// Increment this when the shape of any event payload changes in a
/// backward-incompatible way. The event store uses this to route replayed
/// events through appropriate up-migration logic.
pub const EVENT_SCHEMA_VERSION: &str = "1.0";

/// The clone cache TTL in seconds. API responses from platform searches
/// are cached for this duration to reduce API calls during the clone wizard.
pub const CLONE_CACHE_TTL_SECS: u64 = 300; // 5 minutes

/// The maximum number of repositories returned by a single platform API
/// list call. Larger responses are paginated.
pub const REPO_LIST_PAGE_SIZE: u32 = 100;