[package]
name        = "gm_plugin_local_path"
version     = "0.1.0"
edition     = "2021"
description = "Local Path platform plugin for local filesystem repositories"

[dependencies]
gm_shared   = { path = "../gm_shared" }
gm_ports    = { path = "../gm_ports" }
gm_kernel   = { path = "../gm_kernel" }

tokio       = { workspace = true }
async-trait = { workspace = true }
serde       = { workspace = true }
uuid        = { workspace = true }
tracing     = { workspace = true }
dirs-next   = { workspace = true }
