-- ============================================================
-- Git Multi-Account Manager — Production MySQL Schema
-- Architecture: Microkernel + Hexagonal Core
-- Engine: InnoDB | Charset: utf8mb4 | Collation: utf8mb4_unicode_ci
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO';

CREATE TABLE platforms (
    id              BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36)            NOT NULL,
    name            VARCHAR(50)         NOT NULL,
    display_name    VARCHAR(100)        NOT NULL,
    api_base_url    VARCHAR(500)        NULL,
    ssh_host        VARCHAR(255)        NULL,
    icon_url        VARCHAR(500)        NULL,
    supports_oauth  TINYINT(1)          NOT NULL DEFAULT 0,
    supports_pat    TINYINT(1)          NOT NULL DEFAULT 1,
    supports_ssh    TINYINT(1)          NOT NULL DEFAULT 1,
    supports_https  TINYINT(1)          NOT NULL DEFAULT 1,
    is_active       TINYINT(1)          NOT NULL DEFAULT 1,
    is_self_hosted  TINYINT(1)          NOT NULL DEFAULT 0,
    rate_limit_rpm  INT UNSIGNED        NULL,
    metadata        JSON                NULL,
    created_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_platforms_uuid (uuid),
    UNIQUE KEY uq_platforms_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE accounts (
    id              BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36)            NOT NULL,
    platform_id     BIGINT UNSIGNED     NOT NULL,
    alias           VARCHAR(100)        NOT NULL,
    username        VARCHAR(150)        NOT NULL,
    email           VARCHAR(255)        NOT NULL,
    display_name    VARCHAR(255)        NULL,
    avatar_url      VARCHAR(500)        NULL,
    profile_url     VARCHAR(500)        NULL,
    auth_method     ENUM('ssh','https_pat','https_password','oauth','anonymous') NOT NULL DEFAULT 'ssh',
    ssh_host_alias  VARCHAR(255)        NULL,
    status          ENUM('active','inactive','suspended','token_expired','unverified') NOT NULL DEFAULT 'active',
    is_default      TINYINT(1)          NOT NULL DEFAULT 0,
    last_used_at    TIMESTAMP           NULL,
    last_verified_at TIMESTAMP          NULL,
    metadata        JSON                NULL,
    created_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_accounts_uuid (uuid),
    UNIQUE KEY uq_accounts_alias_platform (alias, platform_id),
    KEY idx_accounts_platform (platform_id),
    KEY idx_accounts_status (status),
    KEY idx_accounts_email (email),
    CONSTRAINT fk_accounts_platform FOREIGN KEY (platform_id) REFERENCES platforms (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE credentials (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                CHAR(36)        NOT NULL,
    account_id          BIGINT UNSIGNED NOT NULL,
    credential_type     ENUM('pat','oauth_access_token','oauth_refresh_token','https_password','ssh_passphrase') NOT NULL,
    encrypted_value     TEXT            NOT NULL,
    encryption_key_id   VARCHAR(100)    NOT NULL,
    iv_hex              VARCHAR(64)     NOT NULL,
    scopes              JSON            NULL,
    expires_at          TIMESTAMP       NULL,
    is_active           TINYINT(1)      NOT NULL DEFAULT 1,
    last_rotated_at     TIMESTAMP       NULL,
    rotation_count      INT UNSIGNED    NOT NULL DEFAULT 0,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_credentials_uuid (uuid),
    KEY idx_credentials_account (account_id),
    KEY idx_credentials_expires (expires_at),
    CONSTRAINT fk_credentials_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ssh_keys (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                CHAR(36)        NOT NULL,
    account_id          BIGINT UNSIGNED NULL,
    name                VARCHAR(150)    NOT NULL,
    key_type            ENUM('ed25519','rsa','ecdsa','dsa') NOT NULL DEFAULT 'ed25519',
    key_size_bits       SMALLINT UNSIGNED NULL,
    public_key          TEXT            NOT NULL,
    fingerprint         VARCHAR(150)    NOT NULL,
    private_key_path    VARCHAR(1000)   NOT NULL,
    comment_email       VARCHAR(255)    NULL,
    passphrase_encrypted TEXT           NULL,
    passphrase_iv_hex   VARCHAR(64)     NULL,
    is_added_to_agent   TINYINT(1)      NOT NULL DEFAULT 0,
    is_active           TINYINT(1)      NOT NULL DEFAULT 1,
    last_tested_at      TIMESTAMP       NULL,
    last_test_status    ENUM('success','failed','untested') NOT NULL DEFAULT 'untested',
    last_test_error     TEXT            NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ssh_keys_uuid (uuid),
    UNIQUE KEY uq_ssh_keys_fingerprint (fingerprint),
    KEY idx_ssh_keys_account (account_id),
    CONSTRAINT fk_ssh_keys_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ssh_host_configs (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                        CHAR(36)        NOT NULL,
    account_id                  BIGINT UNSIGNED NOT NULL,
    ssh_key_id                  BIGINT UNSIGNED NOT NULL,
    host_alias                  VARCHAR(255)    NOT NULL,
    hostname                    VARCHAR(255)    NOT NULL,
    identity_file               VARCHAR(1000)   NOT NULL,
    port                        SMALLINT UNSIGNED NOT NULL DEFAULT 22,
    `user`                      VARCHAR(100)    NOT NULL DEFAULT 'git',
    add_keys_to_agent           TINYINT(1)      NOT NULL DEFAULT 1,
    identity_only               TINYINT(1)      NOT NULL DEFAULT 1,
    strict_host_key_checking    ENUM('yes','no','accept-new') NOT NULL DEFAULT 'accept-new',
    is_synced_to_disk           TINYINT(1)      NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ssh_host_configs_uuid (uuid),
    UNIQUE KEY uq_ssh_host_configs_alias (host_alias),
    KEY idx_ssh_host_configs_account (account_id),
    CONSTRAINT fk_ssh_host_configs_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_ssh_host_configs_key FOREIGN KEY (ssh_key_id) REFERENCES ssh_keys (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE repositories (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                    CHAR(36)        NOT NULL,
    account_id              BIGINT UNSIGNED NOT NULL,
    platform_id             BIGINT UNSIGNED NOT NULL,
    platform_repo_id        VARCHAR(100)    NULL,
    name                    VARCHAR(255)    NOT NULL,
    full_name               VARCHAR(600)    NOT NULL,
    description             TEXT            NULL,
    local_path              VARCHAR(2000)   NULL,
    remote_url              VARCHAR(2000)   NOT NULL,
    clone_url_https         VARCHAR(2000)   NULL,
    clone_url_ssh           VARCHAR(2000)   NULL,
    default_branch          VARCHAR(255)    NOT NULL DEFAULT 'main',
    current_branch          VARCHAR(255)    NULL,
    visibility              ENUM('public','private','internal') NOT NULL DEFAULT 'private',
    is_cloned               TINYINT(1)      NOT NULL DEFAULT 0,
    is_archived             TINYINT(1)      NOT NULL DEFAULT 0,
    is_forked               TINYINT(1)      NOT NULL DEFAULT 0,
    is_empty                TINYINT(1)      NOT NULL DEFAULT 0,
    is_template             TINYINT(1)      NOT NULL DEFAULT 0,
    parent_full_name        VARCHAR(600)    NULL,
    primary_language        VARCHAR(100)    NULL,
    topics                  JSON            NULL,
    size_kb                 INT UNSIGNED    NULL,
    open_issues_count       INT UNSIGNED    NULL DEFAULT 0,
    stargazers_count        INT UNSIGNED    NULL DEFAULT 0,
    forks_count             INT UNSIGNED    NULL DEFAULT 0,
    last_synced_at          TIMESTAMP       NULL,
    last_commit_sha         VARCHAR(100)    NULL,
    last_commit_message     TEXT            NULL,
    last_commit_author      VARCHAR(255)    NULL,
    last_commit_at          TIMESTAMP       NULL,
    clone_depth             INT UNSIGNED    NULL,
    metadata                JSON            NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_repositories_uuid (uuid),
    UNIQUE KEY uq_repositories_full_name_acct (full_name, account_id),
    KEY idx_repositories_account (account_id),
    KEY idx_repositories_platform (platform_id),
    KEY idx_repositories_is_cloned (is_cloned),
    CONSTRAINT fk_repositories_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_repositories_platform FOREIGN KEY (platform_id) REFERENCES platforms (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE git_operations (
    id              BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36)            NOT NULL,
    repository_id   BIGINT UNSIGNED     NOT NULL,
    account_id      BIGINT UNSIGNED     NOT NULL,
    operation_type  ENUM('clone','pull','push','fetch','merge','rebase','commit','checkout','branch_create','branch_delete','branch_rename','tag_create','tag_delete','stash','stash_pop','reset','cherry_pick','revert') NOT NULL,
    status          ENUM('pending','running','success','failed','cancelled','skipped') NOT NULL DEFAULT 'pending',
    triggered_by    ENUM('cli','web','desktop','api','scheduler','workflow','plugin') NOT NULL DEFAULT 'cli',
    branch_source   VARCHAR(255)        NULL,
    branch_target   VARCHAR(255)        NULL,
    remote_name     VARCHAR(100)        NOT NULL DEFAULT 'origin',
    commit_sha      VARCHAR(100)        NULL,
    commit_message  TEXT                NULL,
    options         JSON                NULL,
    raw_command     TEXT                NULL,
    stdout_log      LONGTEXT            NULL,
    stderr_log      LONGTEXT            NULL,
    exit_code       TINYINT             NULL,
    duration_ms     INT UNSIGNED        NULL,
    error_message   TEXT                NULL,
    parent_op_id    BIGINT UNSIGNED     NULL,
    workflow_id     CHAR(36)            NULL,
    started_at      TIMESTAMP           NULL,
    completed_at    TIMESTAMP           NULL,
    created_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_git_operations_uuid (uuid),
    KEY idx_git_ops_repository (repository_id),
    KEY idx_git_ops_account (account_id),
    KEY idx_git_ops_type_status (operation_type, status),
    KEY idx_git_ops_created (created_at),
    CONSTRAINT fk_git_ops_repository FOREIGN KEY (repository_id) REFERENCES repositories (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_git_ops_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_git_ops_parent FOREIGN KEY (parent_op_id) REFERENCES git_operations (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sync_sessions (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                    CHAR(36)        NOT NULL,
    repository_id           BIGINT UNSIGNED NOT NULL,
    account_id              BIGINT UNSIGNED NOT NULL,
    session_type            ENUM('push','pull','full_sync','fetch_only') NOT NULL,
    status                  ENUM('pending','staging','committing','pushing','pulling','merging','success','partial_success','conflict','failed','cancelled') NOT NULL DEFAULT 'pending',
    branch_name             VARCHAR(255)    NOT NULL,
    remote_name             VARCHAR(100)    NOT NULL DEFAULT 'origin',
    commit_message          TEXT            NULL,
    commit_sha_before       VARCHAR(100)    NULL,
    commit_sha_after        VARCHAR(100)    NULL,
    files_staged            INT UNSIGNED    NOT NULL DEFAULT 0,
    files_added             INT UNSIGNED    NOT NULL DEFAULT 0,
    files_modified          INT UNSIGNED    NOT NULL DEFAULT 0,
    files_deleted           INT UNSIGNED    NOT NULL DEFAULT 0,
    files_renamed           INT UNSIGNED    NOT NULL DEFAULT 0,
    commits_pushed          INT UNSIGNED    NOT NULL DEFAULT 0,
    commits_pulled          INT UNSIGNED    NOT NULL DEFAULT 0,
    commits_ahead           INT UNSIGNED    NOT NULL DEFAULT 0,
    commits_behind          INT UNSIGNED    NOT NULL DEFAULT 0,
    conflicts_count         INT UNSIGNED    NOT NULL DEFAULT 0,
    conflict_resolution     ENUM('ours','theirs','manual','abort','none') NOT NULL DEFAULT 'none',
    conflict_files          JSON            NULL,
    options                 JSON            NULL,
    error_message           TEXT            NULL,
    started_at              TIMESTAMP       NULL,
    completed_at            TIMESTAMP       NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_sessions_uuid (uuid),
    KEY idx_sync_sessions_repository (repository_id),
    KEY idx_sync_sessions_account (account_id),
    KEY idx_sync_sessions_status (status),
    KEY idx_sync_sessions_created (created_at),
    CONSTRAINT fk_sync_sessions_repository FOREIGN KEY (repository_id) REFERENCES repositories (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_sync_sessions_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE events (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                CHAR(36)        NOT NULL,
    event_type          VARCHAR(150)    NOT NULL,
    event_version       VARCHAR(20)     NOT NULL DEFAULT '1.0',
    aggregate_type      VARCHAR(100)    NULL,
    aggregate_id        CHAR(36)        NULL,
    payload             JSON            NOT NULL,
    metadata            JSON            NULL,
    is_processed        TINYINT(1)      NOT NULL DEFAULT 0,
    processing_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    first_processed_at  TIMESTAMP       NULL,
    last_error          TEXT            NULL,
    published_at        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_events_uuid (uuid),
    KEY idx_events_type (event_type),
    KEY idx_events_aggregate (aggregate_type, aggregate_id),
    KEY idx_events_published (published_at),
    KEY idx_events_unprocessed (is_processed, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_logs (
    id              BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36)            NOT NULL,
    action          VARCHAR(150)        NOT NULL,
    actor           VARCHAR(255)        NULL,
    resource_type   VARCHAR(100)        NULL,
    resource_id     CHAR(36)            NULL,
    resource_name   VARCHAR(500)        NULL,
    snapshot_before JSON                NULL,
    snapshot_after  JSON                NULL,
    changes         JSON                NULL,
    interface       ENUM('cli','web','desktop','api','scheduler','kernel') NULL,
    ip_address      VARCHAR(45)         NULL,
    session_id      VARCHAR(255)        NULL,
    severity        ENUM('info','warning','critical') NOT NULL DEFAULT 'info',
    correlation_id  CHAR(36)            NULL,
    created_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_audit_logs_uuid (uuid),
    KEY idx_audit_logs_action (action),
    KEY idx_audit_logs_resource (resource_type, resource_id),
    KEY idx_audit_logs_severity (severity),
    KEY idx_audit_logs_created (created_at),
    KEY idx_audit_logs_correlation (correlation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE app_configurations (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    config_key  VARCHAR(255)    NOT NULL,
    config_value JSON           NULL,
    data_type   ENUM('string','integer','boolean','json','array') NOT NULL DEFAULT 'string',
    description TEXT            NULL,
    is_secret   TINYINT(1)      NOT NULL DEFAULT 0,
    is_readonly TINYINT(1)      NOT NULL DEFAULT 0,
    namespace   VARCHAR(100)    NOT NULL DEFAULT 'app',
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_app_config_key (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;