// crates/gm_adapters/src/ssh/ffi.rs
//
// The FFI contract between Rust and the Zig SSH layer.
//
// ── CRITICAL SAFETY RULE ─────────────────────────────────────────────────────
// Every `#[repr(C)]` struct in this file MUST exactly mirror its counterpart
// in `zig_native/src/ssh/*.zig`. Field order, types, and sizes must match.
// Violations cause undefined behaviour — Rust will read wrong memory, producing
// corrupt data that is extremely hard to debug because it doesn't crash.
//
// The Zig source is the authoritative definition. When you change a Zig struct,
// update this file FIRST and recompile both layers together. The `gm_native.h`
// header generated by `zig build` serves as a verification tool:
//   `cat zig_native/zig-out/include/gm_native.h`
//
// ── Memory model across FFI ───────────────────────────────────────────────────
// All data exchange uses caller-allocated fixed-size byte buffers, not heap
// pointers. This means:
//   1. Rust allocates the result struct on the stack before calling the Zig fn.
//   2. Zig writes into that stack memory through the provided pointer.
//   3. No heap allocation crosses the boundary, so there is no allocator
//      mismatch problem (Zig's allocator ≠ Rust's global allocator).
//   4. Buffer overflow is prevented by Zig's `@min(len, buffer.len - 1)` pattern.
//
// ── All-zero validity ────────────────────────────────────────────────────────
// All structs below contain only `u8` arrays, `usize`, `u32`, and `bool`.
// All-zero bytes are valid representations for all of these types. This allows
// the `zeroed()` constructors to use `std::mem::zeroed()` safely.


// ─────────────────────────────────────────────────────────────────────────────
// Key generation
// ─────────────────────────────────────────────────────────────────────────────

/// Result written by `gm_ssh_generate_key`.
/// Mirrors `zig_native/src/ssh/keygen.zig :: KeygenResult`.
#[repr(C)]
pub struct FfiKeygenResult {
    /// The full public key string: "ssh-ed25519 AAAA... user@email"
    pub public_key:     [u8; 4096],
    pub public_key_len: usize,
    /// SHA256 fingerprint: "SHA256:xxxx..."
    pub fingerprint:     [u8; 256],
    pub fingerprint_len: usize,
    /// Human-readable error message; non-empty only when the call returns false.
    pub error_message:   [u8; 512],
    pub error_len:       usize,
}

impl FfiKeygenResult {
    /// Creates a zero-initialised instance.
    ///
    /// # Safety
    /// `FfiKeygenResult` contains only `u8` arrays and `usize` values.
    /// All-zero bytes are valid representations for these types.
    pub fn zeroed() -> Self {
        // SAFETY: see module-level comment on all-zero validity.
        unsafe { std::mem::zeroed() }
    }

    /// Interprets the public key buffer as a UTF-8 string slice.
    /// Returns an empty string if the buffer is not valid UTF-8 (shouldn't happen
    /// for well-formed keys, but we prefer empty to panic).
    pub fn public_key_str(&self) -> &str {
        std::str::from_utf8(&self.public_key[..self.public_key_len]).unwrap_or("")
    }

    pub fn fingerprint_str(&self) -> &str {
        std::str::from_utf8(&self.fingerprint[..self.fingerprint_len]).unwrap_or("")
    }

    pub fn error_str(&self) -> &str {
        std::str::from_utf8(&self.error_message[..self.error_len]).unwrap_or("unknown error")
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Connection testing
// ─────────────────────────────────────────────────────────────────────────────

/// Result written by `gm_ssh_test_connection`.
/// Mirrors `zig_native/src/ssh/connection.zig :: ConnResult`.
#[repr(C)]
pub struct FfiConnectionResult {
    /// Whether authentication succeeded. Not used on the Rust side (the function
    /// return value carries success), but required to keep struct layout in sync.
    pub _success:      u8,
    /// The platform-confirmed username extracted from "Hi username!" (may be empty).
    pub username:      [u8; 256],
    pub username_len:  usize,
    /// Raw response text (stderr + stdout combined) for display.
    pub response:      [u8; 1024],
    pub response_len:  usize,
    /// Error detail populated when the function returns false.
    pub error_message: [u8; 512],
    pub error_len:     usize,
}

impl FfiConnectionResult {
    pub fn zeroed() -> Self {
        // SAFETY: same reasoning as FfiKeygenResult.
        unsafe { std::mem::zeroed() }
    }

    pub fn username_str(&self) -> &str {
        std::str::from_utf8(&self.username[..self.username_len]).unwrap_or("")
    }

    pub fn error_str(&self) -> &str {
        std::str::from_utf8(&self.error_message[..self.error_len]).unwrap_or("unknown error")
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// extern "C" declarations
// ─────────────────────────────────────────────────────────────────────────────
//
// These symbols are resolved at link time against libgm_native.a.
// If a symbol name is misspelled, the build fails with "undefined reference".
// If the parameter types don't match, the behaviour is undefined — the two
// compilers will pass arguments using different calling conventions.

extern "C" {
    /// Generates an SSH key pair at `out_path` using `ssh-keygen`.
    ///
    /// All string parameters are null-terminated C strings. `passphrase` may be
    /// an empty string (not a null pointer) to indicate no passphrase.
    ///
    /// Returns `true` on success, `false` on any failure. On failure, `result.error_*`
    /// fields contain the diagnostic message.
    pub fn gm_ssh_generate_key(
        key_type:   *const std::os::raw::c_char,
        email:      *const std::os::raw::c_char,
        out_path:   *const std::os::raw::c_char,
        passphrase: *const std::os::raw::c_char,
        result:     *mut FfiKeygenResult,
    ) -> bool;

    /// Adds the key at `key_path` to the running SSH agent via `ssh-add`.
    /// `passphrase` may be an empty string for unprotected keys.
    /// Returns `true` on success.
    pub fn gm_ssh_add_to_agent(
        key_path:   *const std::os::raw::c_char,
        passphrase: *const std::os::raw::c_char,
    ) -> bool;

    /// Removes the key at `key_path` from the SSH agent via `ssh-add -d`.
    /// Returns `true` on success.
    pub fn gm_ssh_remove_from_agent(
        key_path: *const std::os::raw::c_char,
    ) -> bool;

    /// Tests an SSH connection to `host` using the identity file at `key_path`.
    /// `timeout_ms` is the connect timeout in milliseconds.
    ///
    /// On success (platform responds), writes the confirmed username into
    /// `result.username`. On failure, writes the error into `result.error_*`.
    pub fn gm_ssh_test_connection(
        host:       *const std::os::raw::c_char,
        key_path:   *const std::os::raw::c_char,
        timeout_ms: u32,
        result:     *mut FfiConnectionResult,
    ) -> bool;

    /// Writes a Host block for `host_alias` into `~/.ssh/config`.
    /// Uses atomic write (temp file → rename) to prevent config corruption.
    /// Returns `true` on success.
    pub fn gm_ssh_write_config_entry(
        host_alias:    *const std::os::raw::c_char,
        hostname:      *const std::os::raw::c_char,
        identity_file: *const std::os::raw::c_char,
        port:          u16,
    ) -> bool;

    /// Removes the Host block for `host_alias` from `~/.ssh/config`.
    /// Returns `true` on success, `true` also if the entry did not exist (idempotent).
    pub fn gm_ssh_remove_config_entry(
        host_alias: *const std::os::raw::c_char,
    ) -> bool;

    /// Returns `true` if the SSH agent socket is accessible.
    pub fn gm_ssh_agent_running() -> bool;

    /// Returns `true` if the key at `key_path` is currently loaded in the SSH agent.
    /// Uses `ssh-add -l` and checks for a matching fingerprint.
    pub fn gm_ssh_agent_has_key(
        key_path: *const std::os::raw::c_char,
    ) -> bool;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper — safe C string construction
// ─────────────────────────────────────────────────────────────────────────────

/// Converts a Rust `&str` to a `std::ffi::CString` for passing to C functions.
///
/// # Panics
/// Panics if the string contains a null byte, which would truncate the C string
/// at an unexpected point. Null bytes are not valid in filesystem paths,
/// SSH host aliases, or email addresses, so this is a programming error.
pub fn to_cstring(s: &str) -> std::ffi::CString {
    std::ffi::CString::new(s).unwrap_or_else(|_| {
        panic!("SSH FFI: string contains a null byte: {s:?}")
    })
}