//! Account-specific error variants.
//!
//! `AccountError` carries typed context about what went wrong during an account
//! operation. Every variant includes the minimum information needed to:
//!   - Display a useful message to the user without a stack trace
//!   - Allow the caller to decide whether to retry, surface the error, or
//!     take a compensating action (e.g. suggest the user pick a different alias)
//!
//! These are domain-level errors — they do not include database error codes or
//! network error details. Those are wrapped by `GitManagerError::Database` or
//! `GitManagerError::Other` at the infrastructure layer before being converted.

use thiserror::Error;
use uuid::Uuid;

/// Errors that can occur during account lifecycle operations.
///
/// The `Display` implementation is generated by `thiserror` from the `#[error]`
/// strings. These strings are what the CLI prints to the terminal and what the
/// web API includes in its error response body.
#[derive(Debug, Error, PartialEq)]
pub enum AccountError {
    /// The requested account UUID does not exist in the store.
    /// Returned by find_by_id() and any operation that requires the account
    /// to already exist (activate, set_default, delete, etc.).
    #[error("Account not found: {uuid}")]
    NotFound { uuid: Uuid },

    /// An account with the same alias already exists for this platform.
    /// Aliases are unique per (platform, alias) pair — the same alias on
    /// different platforms is allowed: "work" on GitHub and "work" on GitLab
    /// are distinct accounts.
    #[error("Account alias '{alias}' already exists for this platform")]
    AliasAlreadyExists { alias: String, platform_id: Uuid },

    /// The provided alias does not meet the format requirements.
    /// Valid aliases: 2–50 lowercase letters, digits, and hyphens only.
    /// No uppercase, no spaces, no underscores, no dots.
    #[error("Invalid alias '{alias}': {reason}")]
    InvalidAlias { alias: String, reason: String },

    /// The provided email address is not a recognizable email format.
    /// We do not perform full RFC 5322 validation — only the basic
    /// structure check (contains @ with a domain containing a dot).
    #[error("Invalid email address: '{email}'")]
    InvalidEmail { email: String },

    /// The username field was empty or contained only whitespace.
    #[error("Username cannot be empty")]
    EmptyUsername,

    /// The account has been suspended and cannot perform any operations.
    /// The user must investigate the platform (e.g. GitHub) to understand
    /// why the account was suspended before the status can change.
    #[error("Account {uuid} is suspended")]
    AccountSuspended { uuid: Uuid },

    /// Attempted to delete the account that is currently marked as the
    /// default for its platform. The user must first set another account
    /// as the default before this one can be removed.
    #[error("Cannot delete the default account without setting another as default first")]
    CannotDeleteDefault,

    /// The platform_id referenced by the account does not exist in the
    /// platform registry table. This usually means the seed data was not
    /// applied or the platform plugin for that platform is not loaded.
    #[error("Platform {platform_id} not found in the registry")]
    PlatformNotFound { platform_id: Uuid },

    /// The requested state transition is not allowed.
    /// For example, trying to activate an already-suspended account.
    /// The `current_status` field contains the string representation of
    /// the account's current status for display in the error message.
    #[error("Cannot transition account {uuid} from status '{current_status}'")]
    InvalidStateTransition { uuid: Uuid, current_status: String },

    /// The platform_id field cannot be changed after an account is created.
    /// If an account needs to move platforms, the old one must be deleted
    /// and a new one created under the new platform.
    #[error("Account platform cannot be changed after creation")]
    CannotChangePlatform,

    /// A database or storage operation failed. This variant carries the
    /// underlying infrastructure error message so that operators can diagnose
    /// the failure without a full stack trace. It is only used by repository
    /// adapter implementations — domain services never produce this variant.
    #[error("Storage operation failed: {0}")]
    StorageFailed(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn not_found_display_includes_uuid() {
        let uuid = Uuid::new_v4();
        let err = AccountError::NotFound { uuid };
        assert!(err.to_string().contains(&uuid.to_string()));
    }

    #[test]
    fn invalid_alias_display_includes_alias_and_reason() {
        let err = AccountError::InvalidAlias {
            alias: "Work".to_string(),
            reason: "uppercase not allowed".to_string(),
        };
        let display = err.to_string();
        assert!(display.contains("Work"));
        assert!(display.contains("uppercase not allowed"));
    }
}