//! The root error type for the entire Git Manager system.
//!
//! `GitManagerError` is what flows out of the domain layer and into the
//! interface plugins (CLI, Web, Desktop). Every `?` on a domain service call
//! ultimately produces a `GitManagerError` at the top of the call stack.
//!
//! # Why a single root error type?
//!
//! Interface plugins need to handle any failure from any domain service in one
//! place. The CLI's error formatter, the web API's error response serializer,
//! and the desktop's error dialog all accept `GitManagerError`. If each domain
//! service returned its own error type, the interface layer would need a
//! different match arm for each — an unmaintainable explosion of variant handling.
//!
//! The trade-off is that `GitManagerError` is coarser than the sub-types.
//! Code that needs to handle an `AccountError::AliasAlreadyExists` specifically
//! must first match on `GitManagerError::Account` and then match on the inner
//! `AccountError`. This is intentional: most error handling at the interface
//! layer is "display this to the user" which does not need the inner type,
//! while domain services that need to react to specific failures match at
//! the sub-type level before the error ever becomes a `GitManagerError`.

use thiserror::Error;
use super::{
    account::AccountError,
    git::GitError,
    plugin::PluginError,
    ssh::SshError,
};

/// The root error type returned by all public domain service methods.
///
/// Interface plugins (CLI, Web, Desktop) receive this type and are responsible
/// for displaying it appropriately for their medium (colored text, JSON response,
/// dialog box). The `Display` implementation is generated by `thiserror` from
/// the `#[error]` annotations and produces human-readable English sentences.
#[derive(Debug, Error)]
pub enum GitManagerError {
    /// An operation on an account (add, remove, activate, set-default) failed.
    #[error("Account error: {0}")]
    Account(#[from] AccountError),

    /// A git operation (clone, pull, push, commit, status) failed.
    #[error("Git error: {0}")]
    Git(#[from] GitError),

    /// An SSH operation (key generation, agent management, connection test) failed.
    #[error("SSH error: {0}")]
    Ssh(#[from] SshError),

    /// A plugin lifecycle operation (load, unload, capability registration) failed.
    #[error("Plugin error: {0}")]
    Plugin(#[from] PluginError),

    /// The application configuration is invalid or could not be loaded.
    /// Contains a human-readable description of the configuration problem.
    #[error("Configuration error: {0}")]
    Config(String),

    /// A database operation failed. The string contains the underlying error
    /// from SQLx (which may include the query text in debug builds).
    #[error("Database error: {0}")]
    Database(String),

    /// An I/O error from the standard library (file not found, permission denied, etc.)
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// A workflow definition is invalid or a workflow step failed.
    #[error("Workflow error: {0}")]
    Workflow(String),

    /// An operation on the credential vault (encrypt, decrypt, derive key) failed.
    /// We do not include the underlying cryptographic error in the message to
    /// avoid leaking information about the encryption scheme to error logs.
    #[error("Credential vault error: {0}")]
    Vault(String),

    /// A catch-all for errors that do not fit a specific category.
    /// Avoid adding new uses of this variant — prefer adding a specific variant
    /// that carries typed context. Existing uses of Other should be migrated
    /// to typed variants as the codebase matures.
    #[error("{0}")]
    Other(String),
}

impl GitManagerError {
    /// Returns a short error category tag suitable for use in structured logs.
    /// The tag is lowercase and stable — it can be used as a metric label.
    pub fn category(&self) -> &'static str {
        match self {
            GitManagerError::Account(_)  => "account",
            GitManagerError::Git(_)      => "git",
            GitManagerError::Ssh(_)      => "ssh",
            GitManagerError::Plugin(_)   => "plugin",
            GitManagerError::Config(_)   => "config",
            GitManagerError::Database(_) => "database",
            GitManagerError::Io(_)       => "io",
            GitManagerError::Workflow(_) => "workflow",
            GitManagerError::Vault(_)    => "vault",
            GitManagerError::Other(_)    => "other",
        }
    }

    /// Returns true if the error is likely transient (network timeout, temporary DB
    /// unavailability) and the operation could be retried with a chance of success.
    /// Returns false for permanent errors (invalid alias, key not found).
    pub fn is_retryable(&self) -> bool {
        match self {
            GitManagerError::Git(e)  => e.is_retryable(),
            GitManagerError::Io(_)   => true,
            GitManagerError::Database(_) => true,
            _ => false,
        }
    }
}

/// Converts SQLx errors to GitManagerError::Database.
/// This implementation lives here because sqlx is a dev/infrastructure
/// concern that gm_shared itself does not import.
/// Adapters that use SQLx implement `From<sqlx::Error>` locally.

#[cfg(test)]
mod tests {
    use super::*;
    use crate::errors::account::AccountError;

    #[test]
    fn account_error_converts_via_question_mark() {
        // Verify that ? on AccountError produces GitManagerError::Account
        fn produce_error() -> Result<(), GitManagerError> {
            Err(AccountError::EmptyUsername)?;
            Ok(())
        }
        let err = produce_error().unwrap_err();
        assert!(matches!(err, GitManagerError::Account(AccountError::EmptyUsername)));
        assert_eq!(err.category(), "account");
    }

    #[test]
    fn io_error_converts_automatically() {
        let io_err = std::io::Error::new(std::io::ErrorKind::NotFound, "file missing");
        let gm_err = GitManagerError::from(io_err);
        assert_eq!(gm_err.category(), "io");
        assert!(!matches!(gm_err, GitManagerError::Other(_)));
    }
}